### ISSUE TITLE
Where is the parameter of soil dataset?

### ISSUE THREAD

**Issue by wanglu2014** [knightlab-analyses/multiomic-cooccurrences#16]
https://github.com/knightlab-analyses/multiomic-cooccurrences/tree/master/scripts
have the parameters for the other 4 datasets. However, where is the parameter that generated the mmvec_rank of soil dataset?

**Comment by mortonjt** [comment]
hmm, not sure why that is not in there ....

There is a tutorial in the main MMvec repo that does use the soils dataset as validation.  That can be seen here: https://github.com/biocore/mmvec/blob/master/examples/soils/run.sh

**Comment by wanglu2014** [comment]
> 
> 
> hmm, not sure why that is not in there ....
> 
> There is a tutorial in the main MMvec repo that does use the soils dataset as validation. That can be seen here: https://github.com/biocore/mmvec/blob/master/examples/soils/run.sh

Thank you for your timely reply! Why you call it P. aeruginosa, since P. aeruginosa not exist in otutable. 
Code:
p_aeruginosa = taxa.loc[(taxa['genus'] == ' g__Pseudomonas').values].index[0] (https://github.com/knightlab-analyses/multiomic-cooccurrences/blob/master/ipynb/Figure4-cystic-fibrosis.ipynb)

**Comment by mortonjt** [comment]
It may not exist in the taxonomy.tsv, but that is mainly due to the resolution of taxonomy classifiers.
If you BLAST that sequence, you can see that P. aeruginosa is the top hit

`TACGAAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCGCGTAGGTGGTTCAGCAAGTTGGATGTGAAATCCCCGGGCTCAACCTGGGAACTGCATCCAAAACTACTGAGCTAGAGTACGGTAGAGGGTGGTGGAATTTCCTG`

**Comment by wanglu2014** [comment]
> 
> 
> It may not exist in the taxonomy.tsv, but that is mainly due to the resolution of taxonomy classifiers.
> If you BLAST that sequence, you can see that P. aeruginosa is the top hit
> 
> `TACGAAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCGCGTAGGTGGTTCAGCAAGTTGGATGTGAAATCCCCGGGCTCAACCTGGGAACTGCATCCAAAACTACTGAGCTAGAGTACGGTAGAGGGTGGTGGAATTTCCTG`

Did you keep the original file 'model.ckpt-3729909.meta'? (ipynb/Figure5-high-fat-diet.ipynb)
